### ISSUE TITLE
genratelabels:-  ModuleNotFoundError: No module named 'cStringIO'

### ISSUE THREAD

**Issue by anaymalpani** [leanderme/sytora#10]
![image](https://user-images.githubusercontent.com/6376413/63244268-8e420200-c27a-11e9-9516-1b4cc585f4f7.png)

Traceback (most recent call last):
  File "generateLabels.py", line 2, in <module>
    import csv, codecs, cStringIO
ModuleNotFoundError: No module named 'cStringIO'

error!!

**Comment by m-root** [comment]
Change to 'import cStringIO' to 'from io import StringIO' if you're using python 3
