### ISSUE TITLE
Umls

### ISSUE THREAD

**Issue by allieonpoppyfield** [leanderme/sytora#2]
Привет. Мне очень жаль, что я тебя опять тревожу. Но это очень важно. Я оформил заявку на получение лицензии UMLS сегодня, ее оформляют в течение пяти дней. Но мне просто необходимо получить архив  сегодня или завтра. Это для моей диссертации. В понедельник я должен ее показать. Могу я тебя попросить поделиться со мной архивом umls-2018AB-full.zip с их сайта? Спасибо.

**Comment by allieonpoppyfield** [comment]
I'm sorry. Here is the translation.

Hey. I'm very sorry to disturb you again. But it is very important. I made an application for a UMLS license today, it is drawn up within five days. But I just need to get the archive today or tomorrow. This is for my dissertation. On Monday, I have to show it. Can I ask you to share the umls-2018AB-full.zip archive with me from their website? Thank.

**Comment by leanderme** [comment]
I‘d really like to help, but I can‘t share the files as it violates the licensing rules. Sorry about that!

**Comment by allieonpoppyfield** [comment]
Oh, no big deal. This will only ruin my life. Thank you for your reply.
