### ISSUE TITLE
Missing en_Diseases.csv in /flaskapp/app/frontend/data/

### ISSUE THREAD

**Issue by AlexHodo** [leanderme/sytora#6]
There is a en_Labels.csv file in there, but I cannot find any English translations of the diseases. Please help!

**Comment by AlexHodo** [comment]
Got it by getting the license.

**Comment by agoel00** [comment]
Hi. I was trying to run the webapp on my local PC but getting confused in how to set it up. Can you share how can I run the flask app locally? Do i need to train all the models again as mentioned in the readme?
