### ISSUE TITLE
i cant find uml.db

### ISSUE THREAD

**Issue by s4surya1swaiting** [leanderme/sytora#7]
conn = sqlite3.connect('./flaskapp/databases/umls.db')
sqlite3.OperationalError: unable to open database file
i cant find any uml.db file

**Comment by leanderme** [comment]
Get a UMLS license to download UMLS lexica & generate the DB (umls.sh). Save the file at the respective directory

**Comment by s4surya1swaiting** [comment]
i downloaded the file but how to geneate ulms.db
all files are extracted but what does it mean "Once you have done this, run this script again with the correct path as the first argument"?
i got 3 folders but how to generate database and run the umls.sh?
Error: cannot open "2019AA/META/*.pipe"

**Comment by s4surya1swaiting** [comment]
well i figured out ,thanks

**Comment by praveenbm5** [comment]
I am trying to use the latest 2020AA release..

When I downloaded the archive... I could not find any umls.sh
